### ISSUE TITLE
Suggestion on the report adjustment

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/dsci522_group21#13]
Summary - precision / recall

Analysis:
 - All variables included in the original data set, with the exception of contact and poutcome, which contained too many unknown examples, were used to fit the model. --> In order to examine the importance of each feature, all the feature variables included in the original data set were used to fit the model. 
 -  The exploratory data analysis focused on understanding variable distributions and relationships between features. It employed visualizations like bar charts and histograms for categorical and numerical variables. Correlation heatmaps were generated to assess the relationships among numerical features and to detect potential multicollinearity. --> examine the distribution of categorical and numerical variables, and Correlation in EDA
- The complete code and methodology are documented in [https://github.com/UBC-MDS/dsci522_group21/blob/main/src/term_deposit_full_analysis.ipynb]. --> put it at the end of Analysis
- --> consider adding "because of interpretability, we employ logistic regression for feature importance"

Data: 
- Additionally, the features job, education, contact, and poutcome include "unknown" entries distinct from null values. Due to insufficient dataset information, proper imputation of these unknown values is not feasible. Specifically, the contact and poutcome columns, containing excessive unknown values, required removal. Eliminating only the unknown values from these columns was deemed impractical as it would significantly reduce the data. On the other hand, the job and education features, despite also containing unknown values, were manageable and were retained by simply removing the unknown entries. --> consider deleting them because the we don't consider removing the "unknown"
- Figure 1: Correlation heatmaps based on two different metrics (Spearman and Pearson correlation coefficients) were generated to investigate the relationships between numerical variables. The Pearson heatmap is shown on this report since it measures linear correlation, which is important to identify potential multicollinearity. --> new paragraph? Pearson correlation coefficients only
 - emphasis precision in our study

Headers:
 - Conclusion / Limitation?

**Comment by JohnShiuMK** [comment]
Data:

Additionally, the features job, education, contact, and poutcome include "unknown" entries distinct from null values. Due to insufficient dataset information, proper imputation of these unknown values is not feasible. Specifically, the contact and poutcome columns, containing excessive unknown values, required removal. Eliminating only the unknown values from these columns was deemed impractical as it would significantly reduce the data. On the other hand, the job and education features, despite also containing unknown values, were manageable and were retained by simply removing the unknown entries. --> we notice that there are many "unknown", and we choose to keep them for ...some reasons......

**Comment by JohnShiuMK** [comment]
- John to exec the full report

**Comment by zgarciaj** [comment]
Branch name --> report_final_adjustments
