### ISSUE TITLE
FYI on Using Pytest

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/dsci522_group21#19]
I added these lines of code (see PR #21) on the top of `tests/test_util.py` to properly import the functions we write in `src/util.py`.

```
import sys
sys.path.append("../")

from src.util import *
```

To use Pytest, `cd` to the `tests` folder and run `pytest` from the terminal. This runs all your tests in `test_util.py`.

**Comment by JohnShiuMK** [comment]
do I need to install pytest in the environment?

**Comment by jy1909** [comment]
Yes, we do. We should probably add `pytest=7.4.3` to `environment.yml` as well.
