### ISSUE TITLE
too many channels in the anaconda environment file may take longer to install the environment

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/dsci522_group21#20]
hello, I am a TA at your course. An advice for you guys. Can you try to ensure that environment installation doesn't take too much time?

**Comment by JohnShiuMK** [comment]
@jy1909 @zgarciaj @zth96, shall we discuss about this tmr please?

**Comment by jy1909** [comment]
I think we should discuss this.

**Comment by zgarciaj** [comment]
I agree, we should discuss it tomorrow. Thank you for the insight, @muntakimrafi !
