### ISSUE TITLE
Corr Heatmaps - 2 Versions

### ISSUE THREAD

**Issue by zgarciaj** [UBC-MDS/dsci522_group21#23]
I've just set up a branch and pull request for the correlation heatmap function. This function takes a data frame and the desired correlation type as inputs and produces a single heatmap. I opted for this version because it aligns closely with our report's approach, where we focused primarily on Pearson's correlation without delving into Spearman's.

However, as we discuss in our last meeting, I also created an alternate function (not yet pushed onto the branch). This version accepts a data frame and generates two heatmaps, one for Spearman's and one for Pearson's correlation, displayed side by side. I'm open to switching to this function if we like it more.

(Full transparency: I've encountered some challenges while working on the tests for the concatenated heatmap function. I'm actively working on resolving these issues before our meeting today. If I'm unable to resolve them in time, and time allows during our meeting, I would welcome the chance to discuss them with the team)

**Comment by JohnShiuMK** [comment]
sure, thanks @zgarciaj 
I'm working on the tests too
