### ISSUE TITLE
Team Work Contract

### ISSUE THREAD

**Issue by zgarciaj** [UBC-MDS/dsci522_group21#3]
The final version of our Team Work Contract is now updated and available in our Google Drive folder.

**Comment by zth96** [comment]
The team contract looks good! Just had it signed.

**Comment by JohnShiuMK** [comment]
https://docs.google.com/document/d/1xfJlOT3WCJVoTsma8-Okwlc1R7I4HWLKiIYjqqnDcNk/edit

I'm good with the contract. Thank you so much @zgarciaj
